trigger:
  - main

pool:
  vmImage: 'windows-latest'
  # name: Default

variables:
  pythonVersion: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'

# ✅ No pip install, manage.py or collectstatic here

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
    archiveFilePatterns: |
      **/*
      !**/venv/**
      !**/__pycache__/**

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'djangoapp'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'az_pipeline'
    appName: 'azure-pipeline'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
